server:
  port: 8666

config-p:
  param1: p1_str
  param2: 2020

appId: test001 #可以通过在启动脚本的时候设置。--appId

spring:
  profiles.active: dev
---
spring:
  profiles: dev
  datasource.hikari:
    jdbc-url: jdbc:mysql://192.168.1.3:33061/spring_boot_demo?allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root123456


---
spring:
  profiles: test
  datasource.hikari:
    jdbc-url: jdbc:mysql://192.168.1.3:33062/spring_boot_demo_test?allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root123456