apiVersion: v1
kind: Service
metadata:
  name: spring-boot-demo-svc
  labels:
    app: spring-boot-demo
spec:
  type: NodePort
  ports:
  - port: 8666
    nodePort: 30001
    protocol: TCP
  selector:
    app: spring-boot-demo